[package]
name = "chat_base"
version = "0.1.0"
authors = ["BB20101997 <bb-github@t-online.de>"]
edition = "2018"

[dependencies]
base_lib = {path = "../base_lib"}
network_lib = {path = "../network_lib"}
